### PR TITLE
Propose less elegant but more specific comparison

### PR DESCRIPTION
**Pull request by smoia**
Closes none

Propose a less elegant, but more specific pattern comparison to find triggers based on names. 

## Proposed Changes

  - Split the regex search into a multi-line for loop
  - Compare the name of the channel to the trigger, not viceversa
  - Remove (filter) empty strings from the channel name split.

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [ ] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [ ] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [ ] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by vinferrer** [comment]
Could you add an example names to the tests that certifies this is working ?

**Comment by vinferrer** [comment]
Could you test a name that wasn't working before?

**Comment by smoia** [comment]
`'CO2'` was problematic before, see [here](https://github.com/physiopy/phys2bids/pull/306#issuecomment-735648802)

**Comment by vinferrer** [comment]
Fair enough, Merging

**Pull request merged**
